language: python

matrix:
  include:
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.5-dev
    - python: nightly
  allow_failures:
  - python: 3.3
  fast_finish: true

install: python setup.py install

services: rabbitmq

before_script:
  - pushd test_project
  - celery -A cosmic_ray.tasks.worker worker &
  - popd

script:
  - py.test cosmic_ray/test
  - cd test_project
  - bash run_tests.sh
