language: python
python:
  - "3.4"

install: python setup.py install

script:
  - python -m unittest discover cosmic_ray/test
  - cd test_project
  - cosmic-ray load cosmic-ray.unittest.conf
  - cosmic-ray load cosmic-ray.pytest.conf