language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.5-dev
    - python: 3.6
    - python: nightly
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - pip install tox
  - python setup.py install
  - pip install -e ".[test]"

services: rabbitmq

before_script:
  - pushd test_project
  - celery -A cosmic_ray.tasks.worker worker &
  - popd

script:
  - if [[ "$python" == "3.6" ]]; then tox; fi
  - cd test_project
  - bash run_tests.sh
