language: python
sudo: required
dist: xenial
matrix:
  include:
  - python: 3.5
    env: TOXENV=py
  - python: 3.6
    env: TOXENV=py
  - python: 3.7
    env: TOXENV=py
  - python: nightly
    env: TOXENV=py
  - python: 3.6
    os: linux
    env: TOXENV=lint,style
  - python: 3.6
    os: linux
    env: TOXENV=docs
  fast_finish: true
  allow_failures:
  - python: nightly
  - python: 3.6
    env: TOXENV=lint,style
env:
  global:
  - PYTEST_ADDOPTS="--e2e-engine=celery4 --e2e-engine=local --e2e-tester=unittest
    --e2e-tester=pytest"
install:
- pip install tox
services: rabbitmq
before_script:
- pushd tests/example_project
- python -m celery worker -A cosmic_ray_celery4_engine.worker &
- popd
script:
- tox
deploy:
  provider: pypi
  user: sixty-north
  password:
    secure: OtGzgIBstMHaLj2gNroxH47W+j6ukzShGU9+PjjWGWuoYlNPoYCWcUsBs5MkmttMeDiZddJX2r9ezQ9872rfc0tRrcakZ6CoAjk4q5eWdrn9tHeivYW3zK9IsL5KHGyPLMrZNVACFvH9J/uHqD3tDlOzO75HNEmmAb6BkNw2sCs=
  distributions: bdist_wheel sdist
  on:
    branch: release
    python: 3.6
before_deploy:
- openssl aes-256-cbc -K $encrypted_6ad9c4041ffc_key -iv $encrypted_6ad9c4041ffc_iv
  -in deploy_key.enc -out deploy_key -d
- python scripts/make_release_tag.py
