language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: nightly
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - python setup.py install
  - pip install -e ".[test]"
  - pushd plugins/execution-engines/celery3
  - python setup.py install
  - cd ../../test-runners/pytest
  - python setup.py install
  - cd ../nose
  - python setup.py install
  - popd
  - cosmic-ray test-runners

services: rabbitmq

before_script:
   # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.5
  - pushd test/test_project
  - celery -A cosmic_ray_celery3_engine.worker worker &
  - popd

script:
  - tox -e py
  - if [[ "$TRAVIS_PYTHON_VERSION" == '3.6' ]]; then tox -e lint,docs; fi
