language: python
python:
  - "3.4"

install: python setup.py install

script: python -m unittest discover cosmic_ray/test
script: cd test_project; cosmic-ray load cosmic-ray.unittest.conf
script: cd test_project; cosmic-ray load cosmic-ray.pytest.conf